Add tracing support for x86
BinaryAnalysisPlatform/qemu pull request #21
Opened 2022-10-09 06:08 UTC by DMaroo

This PR adds tracing support for x86. This will be useful while testing rizinorg/rizin#2747 with `rz-tracetest`.

In it's current state, the generated trace can be successfully read by `libtrace`, and seems to be okay from manual inspection, except it has wrong values for the `rawbytes` field. This results in invalid decompilation on Rizin's side, and therefore inability to use `rz-tracetest`. I believe the that the incorrect `rawbytes` value might be because of incorrect usage of `gen_trace_endframe`.

2022-10-14 07:10 UTC, XVilka requested changes

2022-10-14 13:36 UTC, DMaroo commented on target/i386/trace_helper.c
> +void HELPER(trace_load_reg)(uint32_t reg, target_ulong val)
The register index is always going to be within the bounds of a `uint32_t` integer. Having a compile-time type for it doesn't make sense. Also, if I remember correctly, using `target_ulong` breaks the build, which is why I changed it.

2022-10-19 12:16 UTC, thestr4ng3r requested changes

2022-10-19 12:22 UTC, thestr4ng3r commented on target/i386/tcg/translate.c
> +    tcg_gen_movi_i64(pc_tcg, ctx->pc);
```suggestion
    tcg_gen_movi_i64(pc_tcg, ctx->base.pc_next);
```
This will fix incorrect addresses in the frames.

2022-10-28 11:30 UTC, DMaroo commented on target/i386/trace_helper.c
> +OperandInfo *load_store_mem(uint64_t addr, int ls, const void *data, size_t data_size)
The signature was changed in the ARM lifting, so I will go ahead with the new signature.

2022-10-28 11:32 UTC, DMaroo commented
The x86 tracing is now working. The generated traces seem to be correct and I am able to run https://github.com/rizinorg/rz-tracetest on them. But I would advise not to merge this until I am done testing the IL, because there may be bugs. Once the trace testing is complete, we can be confident to merge it.

2023-02-23 09:52 UTC, XVilka commented
@DMaroo have been there any updates since? How close is the testing?

2023-02-24 01:15 UTC, DMaroo commented
I didn't get much time to work on this in the past few months. I am yet to verify the tracing for segment registers. I think I will be fairly confident about the tracing within 3 weeks. The PR can be merged then. Any other changes can then be incrementally merged, if needed.

2023-05-08 03:12 UTC, XVilka commented
@DMaroo have you had any chance to look at this?

2023-06-11 05:41 UTC, DMaroo commented
I think this the tracing instrumentation is majorly done for x86 and we can merge this now. We can address missing cases later on a case-by-case basis.

2023-06-12 02:28 UTC, XVilka approved these changes

2023-06-14 01:59 UTC, XVilka approved these changes

2023-06-14 16:04 UTC, ivg approved these changes
Awesome!

2023-06-15 01:15 UTC, merged