Add Mips Tracewrap Support (WIP)
BinaryAnalysisPlatform/qemu pull request #26
Opened 2023-07-04 12:16 UTC by brightprogrammer

This PR adds MIPS support in tracewrap

2023-08-01 09:10 UTC, XVilka requested changes
Please avoid unnecessary changes

2023-08-01 09:10 UTC, XVilka commented on include/qemu/bswap.h
> +#include "osdep.h"
Is this necessary change? It's preferable to keep unrelated changes to the minimum, so that updating the QEMU base would be easier.

2023-08-01 09:10 UTC, XVilka commented on include/fpu/softfloat.h
> +#include <stdbool.h>
Is this necessary?

2023-08-01 09:10 UTC, XVilka commented on include/fpu/softfloat-types.h
> +#include <stdint.h>
Same - I believe it's unnecessary and should work without

2023-08-01 09:10 UTC, XVilka commented on util/async.c
> +    BHListSlice *slice = g_malloc(sizeof(BHListSlice));
Why this? Please see also the mainstream QEMU of newer versions for a better fix. Using it would make updating QEMU base easier.

2023-08-01 09:10 UTC, XVilka commented on stubs/replay-tools.c
> +int64_t replay_save_clock(ReplayClockKind kind, int64_t clock, int64_t raw_icount)
I see you imported the change from QEMU mainstream. Please cherry-pick the whole commit of theirs, it will make rebase easier.

2023-08-01 09:10 UTC, XVilka commented on qobject/block-qdict.c
> +        size_t snprintf_ret;
Unnecessary change

2025-06-19 11:12 UTC, Rot127 commented
I'll close these because I'll start implement the trace with the TCG API now: https://github.com/BinaryAnalysisPlatform/qemu/issues/24

2025-06-19 11:12 UTC, closed without merging