Hexagon trace support
BinaryAnalysisPlatform/qemu pull request #34
Opened 2023-11-28 19:42 UTC by Rot127

Adds the trace support for the Hexagon architecture.

@ivg Please merge this into `tracewrap-8.1-hexagon` once everything looks good to you.
Also, no need to squash this. Since it is only for Hexagon anyways.

2023-11-29 15:43 UTC, ivg requested changes

2023-11-29 15:43 UTC, ivg commented on .github/workflows/build.yaml
> +        ./configure --prefix=$HOME --with-tracewrap="$HOME"/bap-frames --target-list=hexagon-linux-user
to make opam-installed stuff visible (i.e., to update the PATH variable and the rest) you can use `opam exec --`, e.g.,
```suggestion
        opam exec -- ./configure --prefix=$HOME --with-tracewrap="$HOME"/bap-frames --target-list=hexagon-linux-user
```

2023-11-29 15:44 UTC, ivg commented
also, don't forget to rebase, so that the remove lockdown action is gone)

2023-12-01 21:55 UTC, ivg commented
> @ivg Please merge this into tracewrap-8.1-hexagon once everything looks good to you.

I can only merge PRs to the branch you're requesting :)

2023-12-01 22:08 UTC, ivg requested changes

2023-12-01 22:08 UTC, ivg commented on .github/workflows/build.yaml
>          git clone --depth 1 http://github.com/BinaryAnalysisPlatform/bap-frames.git
It is better to use the dedicated workflow for cloning (I see there are weird messages during cloning the log), here's how to use it:
```
      - name: Checkout bap-frames
        uses: actions/checkout@v3
        with:
          repository: BinaryAnalysisPlatform/bap-frames
          path: bap-frames

2023-12-01 22:22 UTC, Rot127 commented
@ivg Thanks. Added the branch and changed the base here.

2023-12-01 22:46 UTC, closed without merging